#!/bin/bash

WALLPAPERS_DIRECTORY="~/Pictures/wallpapers-unsplash";
URL="https://api.unsplash.com/photos/random/?client_id=09987f8449b94d9e98b41bf14747596e5557b2f7878853399d969bf38a54a611";

# Check if folder for pictures exist
if [[ -d "~/Pictures/wallpapers-unsplash" ]]; then
  mkdir ~/Pictures/wallpapers-unsplash/
fi

# Get random picture from Unsplash
function getPicture() {
  data=$(curl -s ${URL});
  picture=$(echo ${data} | json_pp | grep "\"full\"" | awk -F "\"" '{print $4}' );
  width=$(echo ${data} | json_pp | grep "\"width\"" | awk -F ":" '{print $2}' | tr ',' ' ');
  height=$(echo ${data} | json_pp | grep "\"height\"" | awk -F ":" '{print $2}' | tr ',' ' ' );
  ids=$(echo ${data} | json_pp | grep "\"id\"" | awk -F "\"" '{print $4}' );
  parsedIds=(${ids}); # first id of the author, second of the picture
  name=${parsedIds[1]};

  if [[ $((width / height)) != 1 ]]; then
    getPicture
  else
    echo ${picture} ${name};
    return
  fi
}

# Save picture
function savePicture() {
  curl ${1} -s -o ${WALLPAPERS_DIRECTORY}${2}.jpg;
}

# Change wallpaper value
function setWallpaper() {
  # TODO: Properly update image and path
  sqlite3 ~/Library/Application\ Support/Dock/desktoppicture.db \
  "
  INSERT OR REPLACE INTO 'main'.'data' ('value') VALUES ('${WALLPAPERS_DIRECTORY}');

  INSERT OR REPLACE INTO 'main'.'data' ('value') VALUES ('${WALLPAPERS_DIRECTORY}${1}.jpg');
  ";
  killall Dock;
}

getPicture
savePicture ${picture} ${name}
setWallpaper ${name}